#!/usr/bin/env Rscript

# Usage: script to run DE analysis using DESeq2 on single-cell RNA-seq clusters generated by Seurat. The DE analysis is performed on the cell type cluster specified on the command line. The command line argument for cell type cluster should contain a value output from levels(seurat@ident)

library(dplyr)
library(Matrix)
library(DESeq2)
library(tibble)
library(BiocParallel)

load("data/DESeq_object.rda")

# Use command line argument for cluster ID
options(echo=TRUE)
args <- commandArgs(trailingOnly = TRUE)

dds_cluster <- dds[ , dds$ident %in% as.character(args[1])]

dds_cluster$ident <- droplevels(dds_cluster$ident)
dds_cluster$sample <- droplevels(dds_cluster$sample)

dds_cluster_lrt <- DESeq(dds_cluster,
        test = "LRT",
        full = ~ nUMI + Phase + condition,
        reduced = ~ nUMI + Phase,
        sfType = "poscounts",
        minmu = 1e-6,
        minRep = Inf,
        parallel = TRUE,
        BPPARAM = MulticoreParam(8))

print("working on next cluster conditionA_vs_conditionB")

# conditionA vs. conditionB
    contrast_conditionA_vs_conditionB <- c("condition","conditionA","conditionB")
    dds_conditionA_vs_conditionB_lrt_results_unshrunken <- results(dds_cluster_lrt, contrast=contrast_conditionA_vs_conditionB, cooksCutoff = FALSE)
dds_conditionA_vs_conditionB_lrt_results_shrunken <- lfcShrink(dds_cluster_lrt,contrast = contrast_conditionA_vs_conditionB, res = dds_conditionA_vs_conditionB_lrt_results_unshrunken)
    save(dds_cluster_lrt, dds_conditionA_vs_conditionB_lrt_results_unshrunken,dds_conditionA_vs_conditionB_lrt_results_shrunken,file = paste0("results/dds_results_conditionA_vs_conditionB",as.character(args[1]),".Rdata"))

print("moving on to conditionA_vs_conditionC")

# conditionA vs. conditionC
contrast_conditionA_vs_conditionC <- c("condition","conditionA","conditionC")
    dds_conditionA_vs_conditionC_lrt_results_unshrunken <- results(dds_cluster_lrt, contrast=contrast_conditionA_vs_conditionC, cooksCutoff = FALSE)
dds_conditionA_vs_conditionC_lrt_results_shrunken <- lfcShrink(dds_cluster_lrt,contrast = contrast_conditionA_vs_conditionC, res = dds_conditionA_vs_conditionC_lrt_results_unshrunken)
    save(dds_cluster_lrt, dds_conditionA_vs_conditionC_lrt_results_unshrunken,dds_conditionA_vs_conditionC_lrt_results_shrunken,file = paste0("results/dds_results_conditionA_vs_conditionC",as.character(args[1]),".Rdata"))

print("moving on to conditionB_vs_conditionC")

# conditionB vs. conditionC
contrast_conditionB_vs_conditionC <- c("condition","conditionB","conditionC")
    dds_conditionB_vs_conditionC_lrt_results_unshrunken <- results(dds_cluster_lrt, contrast=contrast_conditionB_vs_conditionC, cooksCutoff = FALSE)
dds_conditionB_vs_conditionC_lrt_results_shrunken <- lfcShrink(dds_cluster_lrt,contrast = contrast_conditionB_vs_conditionC, res = dds_conditionB_vs_conditionC_lrt_results_unshrunken)
    save(dds_cluster_lrt, dds_conditionB_vs_conditionC_lrt_results_unshrunken,dds_conditionB_vs_conditionC_lrt_results_shrunken,file = paste0("results/dds_results_conditionB_vs_conditionC",as.character(args[1]),".Rdata"))
